# Generated by Django 2.2.2 on 2019-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', upload_to='static/image/Activity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', upload_to='static/image/UserAvatar'),
        ),
    ]
