# Generated by Django 2.2.2 on 2019-06-07 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serviceWeb', '0002_auto_20190606_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='addr',
            field=models.CharField(db_column='addr', default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
